"""Add chunk_type to DocumentChunk

Revision ID: 728be9a2c3a6
Revises: 4a102a34b026
Create Date: 2025-06-12 23:45:27.789217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728be9a2c3a6'
down_revision = '4a102a34b026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 